export const ALL_CURRENCIES = [
  { label: 'TRY - Türk Lirası', value: 'TRY' },
  { label: 'USD - Amerikan Doları', value: 'USD' },
  { label: 'EUR - Euro', value: 'EUR' },
  { label: 'GBP - İngiliz Sterlini', value: 'GBP' },
  { label: 'AED - Birleşik Arap Emirlikleri Dirhemi', value: 'AED' },
  { label: 'AFN - Afganistan Afganisi', value: 'AFN' },
  { label: 'ALL - Arnavutluk Leki', value: 'ALL' },
  { label: 'AMD - Ermenistan Dramı', value: 'AMD' },
  { label: 'ANG - Hollanda Antilleri Guldeni', value: 'ANG' },
  { label: 'AOA - Angola Kvanzası', value: 'AOA' },
  { label: 'ARS - Arjantin Pesosu', value: 'ARS' },
  { label: 'AUD - Avustralya Doları', value: 'AUD' },
  { label: 'AWG - Aruba Florini', value: 'AWG' },
  { label: 'AZN - Azerbaycan Manatı', value: 'AZN' },
  { label: 'BAM - Bosna-Hersek Değiştirilebilir Markı', value: 'BAM' },
  { label: 'BBD - Barbados Doları', value: 'BBD' },
  { label: 'BDT - Bangladeş Takası', value: 'BDT' },
  { label: 'BGN - Bulgar Levası', value: 'BGN' },
  { label: 'BHD - Bahreyn Dinarı', value: 'BHD' },
  { label: 'BIF - Burundi Frangı', value: 'BIF' },
  { label: 'BMD - Bermuda Doları', value: 'BMD' },
  { label: 'BND - Brunei Doları', value: 'BND' },
  { label: 'BOB - Bolivya Bolivyanosu', value: 'BOB' },
  { label: 'BRL - Brezilya Reali', value: 'BRL' },
  { label: 'BSD - Bahama Doları', value: 'BSD' },
  { label: 'BTN - Butan Ngultrumu', value: 'BTN' },
  { label: 'BWP - Botsvana Pulası', value: 'BWP' },
  { label: 'BYN - Belarus Rublesi', value: 'BYN' },
  { label: 'BZD - Belize Doları', value: 'BZD' },
  { label: 'CAD - Kanada Doları', value: 'CAD' },
  { label: 'CDF - Kongo Frangı', value: 'CDF' },
  { label: 'CHF - İsviçre Frangı', value: 'CHF' },
  { label: 'CLP - Şili Pesosu', value: 'CLP' },
  { label: 'CNY - Çin Yuanı', value: 'CNY' },
  { label: 'COP - Kolombiya Pesosu', value: 'COP' },
  { label: 'CRC - Kosta Rika Kolonu', value: 'CRC' },
  { label: 'CUP - Küba Pesosu', value: 'CUP' },
  { label: 'CVE - Cape Verde Esküdosu', value: 'CVE' },
  { label: 'CZK - Çek Korunası', value: 'CZK' },
  { label: 'DJF - Cibuti Frangı', value: 'DJF' },
  { label: 'DKK - Danimarka Kronu', value: 'DKK' },
  { label: 'DOP - Dominik Pesosu', value: 'DOP' },
  { label: 'DZD - Cezayir Dinarı', value: 'DZD' },
  { label: 'EGP - Mısır Lirası', value: 'EGP' },
  { label: 'ERN - Eritre Nakfası', value: 'ERN' },
  { label: 'ETB - Etiyopya Birri', value: 'ETB' },
  { label: 'FJD - Fiji Doları', value: 'FJD' },
  { label: 'FKP - Falkland Adaları Lirası', value: 'FKP' },
  { label: 'GEL - Gürcistan Larisi', value: 'GEL' },
  { label: 'GHS - Gana Sedisi', value: 'GHS' },
  { label: 'GIP - Cebelitarık Lirası', value: 'GIP' },
  { label: 'GMD - Gambiya Dalasisi', value: 'GMD' },
  { label: 'GNF - Gine Frangı', value: 'GNF' },
  { label: 'GTQ - Guatemala Ketzali', value: 'GTQ' },
  { label: 'GYD - Guyana Doları', value: 'GYD' },
  { label: 'HKD - Hong Kong Doları', value: 'HKD' },
  { label: 'HNL - Honduras Lempirası', value: 'HNL' },
  { label: 'HRK - Hırvatistan Kunası', value: 'HRK' },
  { label: 'HTG - Haiti Gourdesi', value: 'HTG' },
  { label: 'HUF - Macar Forinti', value: 'HUF' },
  { label: 'IDR - Endonezya Rupisi', value: 'IDR' },
  { label: 'ILS - Yeni İsrail Şekeli', value: 'ILS' },
  { label: 'INR - Hindistan Rupisi', value: 'INR' },
  { label: 'IQD - Irak Dinarı', value: 'IQD' },
  { label: 'IRR - İran Riyali', value: 'IRR' },
  { label: 'ISK - İzlanda Kronu', value: 'ISK' },
  { label: 'JMD - Jamaika Doları', value: 'JMD' },
  { label: 'JOD - Ürdün Dinarı', value: 'JOD' },
  { label: 'JPY - Japon Yeni', value: 'JPY' },
  { label: 'KES - Kenya Şilini', value: 'KES' },
  { label: 'KGS - Kırgızistan Somu', value: 'KGS' },
  { label: 'KHR - Kamboçya Rieli', value: 'KHR' },
  { label: 'KMF - Komorlar Frangı', value: 'KMF' },
  { label: 'KPW - Kuzey Kore Wonu', value: 'KPW' },
  { label: 'KRW - Güney Kore Wonu', value: 'KRW' },
  { label: 'KWD - Kuveyt Dinarı', value: 'KWD' },
  { label: 'KYD - Cayman Adaları Doları', value: 'KYD' },
  { label: 'KZT - Kazakistan Tengesi', value: 'KZT' },
  { label: 'LAK - Laos Kipi', value: 'LAK' },
  { label: 'LBP - Lübnan Lirası', value: 'LBP' },
  { label: 'LKR - Sri Lanka Rupisi', value: 'LKR' },
  { label: 'LRD - Liberya Doları', value: 'LRD' },
  { label: 'LSL - Lesotho Lotisi', value: 'LSL' },
  { label: 'LYD - Libya Dinarı', value: 'LYD' },
  { label: 'MAD - Fas Dirhemi', value: 'MAD' },
  { label: 'MDL - Moldova Leyi', value: 'MDL' },
  { label: 'MGA - Madagaskar Ariarisi', value: 'MGA' },
  { label: 'MKD - Makedonya Dinarı', value: 'MKD' },
  { label: 'MMK - Myanmar Kyatı', value: 'MMK' },
  { label: 'MNT - Moğolistan Tugriki', value: 'MNT' },
  { label: 'MOP - Makao Patakası', value: 'MOP' },
  { label: 'MRU - Moritanya Ugiyası', value: 'MRU' },
  { label: 'MUR - Mauritius Rupisi', value: 'MUR' },
  { label: 'MVR - Maldivler Rufiyaası', value: 'MVR' },
  { label: 'MWK - Malavi Kvaçası', value: 'MWK' },
  { label: 'MXN - Meksika Pesosu', value: 'MXN' },
  { label: 'MYR - Malezya Ringgiti', value: 'MYR' },
  { label: 'MZN - Mozambik Metikali', value: 'MZN' },
  { label: 'NAD - Namibya Doları', value: 'NAD' },
  { label: 'NGN - Nijerya Nairası', value: 'NGN' },
  { label: 'NIO - Nikaragua Kordobası', value: 'NIO' },
  { label: 'NOK - Norveç Kronu', value: 'NOK' },
  { label: 'NPR - Nepal Rupisi', value: 'NPR' },
  { label: 'NZD - Yeni Zelanda Doları', value: 'NZD' },
  { label: 'OMR - Umman Riyali', value: 'OMR' },
  { label: 'PAB - Panama Balboası', value: 'PAB' },
  { label: 'PEN - Peru Solü', value: 'PEN' },
  { label: 'PGK - Papua Yeni Gine Kinası', value: 'PGK' },
  { label: 'PHP - Filipinler Pesosu', value: 'PHP' },
  { label: 'PKR - Pakistan Rupisi', value: 'PKR' },
  { label: 'PLN - Polonya Zlotisi', value: 'PLN' },
  { label: 'PYG - Paraguay Guaranisi', value: 'PYG' },
  { label: 'QAR - Katar Riyali', value: 'QAR' },
  { label: 'RON - Rumen Leyi', value: 'RON' },
  { label: 'RSD - Sırp Dinarı', value: 'RSD' },
  { label: 'RUB - Rus Rublesi', value: 'RUB' },
  { label: 'RWF - Ruanda Frangı', value: 'RWF' },
  { label: 'SAR - Suudi Arabistan Riyali', value: 'SAR' },
  { label: 'SBD - Solomon Adaları Doları', value: 'SBD' },
  { label: 'SCR - Seyşeller Rupisi', value: 'SCR' },
  { label: 'SDG - Sudan Lirası', value: 'SDG' },
  { label: 'SEK - İsveç Kronu', value: 'SEK' },
  { label: 'SGD - Singapur Doları', value: 'SGD' },
  { label: 'SHP - Saint Helena Lirası', value: 'SHP' },
  { label: 'SLL - Sierra Leone Leonesi', value: 'SLL' },
  { label: 'SOS - Somali Şilini', value: 'SOS' },
  { label: 'SRD - Surinam Doları', value: 'SRD' },
  { label: 'SSP - Güney Sudan Lirası', value: 'SSP' },
  { label: 'STN - Sao Tome ve Principe Dobrası', value: 'STN' },
  { label: 'SVC - El Salvador Kolonu', value: 'SVC' },
  { label: 'SYP - Suriye Lirası', value: 'SYP' },
  { label: 'SZL - Esvatini Lilangenisi', value: 'SZL' },
  { label: 'THB - Tayland Bahtı', value: 'THB' },
  { label: 'TJS - Tacikistan Somonisi', value: 'TJS' },
  { label: 'TMT - Türkmenistan Manatı', value: 'TMT' },
  { label: 'TND - Tunus Dinarı', value: 'TND' },
  { label: 'TOP - Tonga Paʻangası', value: 'TOP' },
  { label: 'TTD - Trinidad ve Tobago Doları', value: 'TTD' },
  { label: 'TWD - Yeni Tayvan Doları', value: 'TWD' },
  { label: 'TZS - Tanzanya Şilini', value: 'TZS' },
  { label: 'UAH - Ukrayna Grivnası', value: 'UAH' },
  { label: 'UGX - Uganda Şilini', value: 'UGX' },
  { label: 'UYU - Uruguay Pesosu', value: 'UYU' },
  { label: 'UZS - Özbekistan Somu', value: 'UZS' },
  { label: 'VES - Venezuela Bolivarı', value: 'VES' },
  { label: 'VND - Vietnam Dongu', value: 'VND' },
  { label: 'VUV - Vanuatu Vatusu', value: 'VUV' },
  { label: 'WST - Samoa Talası', value: 'WST' },
  { label: 'XAF - Orta Afrika CFA Frangı', value: 'XAF' },
  { label: 'XCD - Doğu Karayip Doları', value: 'XCD' },
  { label: 'XOF - Batı Afrika CFA Frangı', value: 'XOF' },
  { label: 'XPF - CFP Frangı', value: 'XPF' },
  { label: 'YER - Yemen Riyali', value: 'YER' },
  { label: 'ZAR - Güney Afrika Randı', value: 'ZAR' },
  { label: 'ZMW - Zambiya Kvaçası', value: 'ZMW' },
  { label: 'ZWL - Zimbabve Doları', value: 'ZWL' }
]
